//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BravoVets.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    using BravoVets.DomainObject;

    public partial class BravoVetsDbEntities : DbContext
    {
        public BravoVetsDbEntities()
            : base("name=BravoVetsDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityType> ActivityTypes { get; set; }
        public virtual DbSet<BravoVetsCountry> BravoVetsCountries { get; set; }
        public virtual DbSet<BravoVetsLanguage> BravoVetsLanguages { get; set; }
        public virtual DbSet<BravoVetsStatu> BravoVetsStatus { get; set; }
        public virtual DbSet<BravoVetsUser> BravoVetsUsers { get; set; }
        public virtual DbSet<BravoVetsUserActivity> BravoVetsUserActivities { get; set; }
        public virtual DbSet<ChannelType> ChannelTypes { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<MerckLfwUser> MerckLfwUsers { get; set; }
        public virtual DbSet<QueueContent> QueueContents { get; set; }
        public virtual DbSet<QueueContentAttachment> QueueContentAttachments { get; set; }
        public virtual DbSet<SocialPlatform> SocialPlatforms { get; set; }
        public virtual DbSet<SyndicatedContent> SyndicatedContents { get; set; }
        public virtual DbSet<SyndicatedContentAttachment> SyndicatedContentAttachments { get; set; }
        public virtual DbSet<SyndicatedContentPostType> SyndicatedContentPostTypes { get; set; }
        public virtual DbSet<SyndicatedContentTag> SyndicatedContentTags { get; set; }
        public virtual DbSet<SyndicatedContentType> SyndicatedContentTypes { get; set; }
        public virtual DbSet<SyndicatedContentUser> SyndicatedContentUsers { get; set; }
        public virtual DbSet<Veterinarian> Veterinarians { get; set; }
        public virtual DbSet<VeterinarianFacility> VeterinarianFacilities { get; set; }
        public virtual DbSet<VeterinarianFacilityChannel> VeterinarianFacilityChannels { get; set; }
        public virtual DbSet<VeterinarianSocialIntegration> VeterinarianSocialIntegrations { get; set; }
        public virtual DbSet<QueueContentDeliveryLog> QueueContentDeliveryLogs { get; set; }
        public virtual DbSet<FeaturedContent> FeaturedContents { get; set; }
        public virtual DbSet<SyndicatedContentLink> SyndicatedContentLinks { get; set; }
    }
}
