//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Script Date: 3/31/2014 5:24 PM  - ErikEJ.SqlCeScripting version 3.5.2.37
        ///CREATE TABLE [SyndicatedContentType] (
        ///  [SyndicatedContentTypeId] int IDENTITY (1,1) NOT NULL
        ///, [SyndicatedContentTypeName] nvarchar(128) NOT NULL
        ///, [CreateDateUtc] datetime NOT NULL
        ///);
        ///GO
        ///CREATE TABLE [SyndicatedContentPostType] (
        ///  [SyndicatedContentPostTypeId] int IDENTITY (1,1) NOT NULL
        ///, [SyndicatedContentPostTypeName] nvarchar(200) NOT NULL
        ///, [CreateDateUtc] datetime NOT NULL
        ///, [ModifiedDateUtc] datetime NOT NULL
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bvsqlce {
            get {
                return ResourceManager.GetString("bvsqlce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Script Date: 3/31/2014 6:31 PM  - ErikEJ.SqlCeScripting version 3.5.2.37
        ///SET IDENTITY_INSERT [SyndicatedContentType] ON;
        ///GO
        ///INSERT INTO [SyndicatedContentType] ([SyndicatedContentTypeId],[SyndicatedContentTypeName],[CreateDateUtc]) VALUES (1,N&apos;Trending Topics&apos;,{ts &apos;2014-03-01 02:00:51.090&apos;});
        ///GO
        ///INSERT INTO [SyndicatedContentType] ([SyndicatedContentTypeId],[SyndicatedContentTypeName],[CreateDateUtc]) VALUES (2,N&apos;Social Tips&apos;,{ts &apos;2014-03-01 02:00:51.090&apos;});
        ///GO
        ///INSERT INTO [SyndicatedContentType]  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bvsqlce_data {
            get {
                return ResourceManager.GetString("bvsqlce_data", resourceCulture);
            }
        }
    }
}
