//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BravoVets.DomainObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class BravoVetsStatu
    {
        public BravoVetsStatu()
        {
            this.BravoVetsUsers = new HashSet<BravoVetsUser>();
            this.QueueContents = new HashSet<QueueContent>();
            this.SyndicatedContents = new HashSet<SyndicatedContent>();
            this.SyndicatedContentUsers = new HashSet<SyndicatedContentUser>();
        }
    
        public int BravoVetsStatusId { get; set; }
        public string StatusName { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime ModifiedDateUtc { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ICollection<BravoVetsUser> BravoVetsUsers { get; set; }
        public virtual ICollection<QueueContent> QueueContents { get; set; }
        public virtual ICollection<SyndicatedContent> SyndicatedContents { get; set; }
        public virtual ICollection<SyndicatedContentUser> SyndicatedContentUsers { get; set; }
    }
}
