//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BravoVets.DomainObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class BravoVetsLanguage
    {
        public BravoVetsLanguage()
        {
            this.BravoVetsCountries = new HashSet<BravoVetsCountry>();
        }
    
        public int BravoVetsLanguageId { get; set; }
        public string LanguageName { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime ModifiedDateUtc { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ICollection<BravoVetsCountry> BravoVetsCountries { get; set; }
    }
}
