//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BravoVets.DomainObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class BravoVetsUser
    {
        public BravoVetsUser()
        {
            this.BravoVetsUserActivities = new HashSet<BravoVetsUserActivity>();
            this.QueueContents = new HashSet<QueueContent>();
            this.SyndicatedContentUsers = new HashSet<SyndicatedContentUser>();
        }
    
        public int BravoVetsUserId { get; set; }
        public int VeterinarianId { get; set; }
        public int MerckId { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string Lastname { get; set; }
        public int BravoVetsCountryId { get; set; }
        public string CultureName { get; set; }
        public Nullable<int> RepContactId { get; set; }
        public bool EmailOptIn { get; set; }
        public bool AcceptedTandC { get; set; }
        public int BravoVetsStatusId { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime ModifiedDateUtc { get; set; }
        public bool Deleted { get; set; }
    
        public virtual BravoVetsCountry BravoVetsCountry { get; set; }
        public virtual BravoVetsStatu BravoVetsStatu { get; set; }
        public virtual Veterinarian Veterinarian { get; set; }
        public virtual ICollection<BravoVetsUserActivity> BravoVetsUserActivities { get; set; }
        public virtual ICollection<QueueContent> QueueContents { get; set; }
        public virtual ICollection<SyndicatedContentUser> SyndicatedContentUsers { get; set; }
    }
}
