//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BravoVets.DomainObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelType
    {
        public ChannelType()
        {
            this.VeterinarianFacilityChannels = new HashSet<VeterinarianFacilityChannel>();
        }
    
        public int ChannelTypeId { get; set; }
        public string ChannelTypeName { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime ModifiedDateUtc { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ICollection<VeterinarianFacilityChannel> VeterinarianFacilityChannels { get; set; }
    }
}
