//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BravoVets.DomainObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeaturedContent
    {
        public int FeaturedContentId { get; set; }
        public int SyndicatedContentTypeId { get; set; }
        public string ContentFileName { get; set; }
        public string ContentExtension { get; set; }
        public byte[] ContentThumbnail { get; set; }
        public byte[] ContentFile { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime ModifiedDateUtc { get; set; }
        public int BravoVetsCountryId { get; set; }
    
        public virtual BravoVetsCountry BravoVetsCountry { get; set; }
    }
}
