//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BravoVets.DomainObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerckLfwUser
    {
        public int MerckLfwUserId { get; set; }
        public int MerckId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CountryOriginIso { get; set; }
        public string Occupation { get; set; }
        public string EmailAddress { get; set; }
        public string LanguageIsoCode { get; set; }
        public string IP { get; set; }
        public string UA { get; set; }
        public string LoginGUID { get; set; }
        public string ForgeryID { get; set; }
        public string WebsiteProperties { get; set; }
        public string AccessOnGroups { get; set; }
        public string CookiesEnabled { get; set; }
        public string LfwMessage { get; set; }
    }
}
