//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BravoVets.DomainObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueContent
    {
        public int QueueContentId { get; set; }
        public int BravoVetsCountryId { get; set; }
        public int BravoVetsUserId { get; set; }
        public Nullable<int> SyndicatedContentPostTypeId { get; set; }
        public string ContentText { get; set; }
        public Nullable<int> SyndicatedContentId { get; set; }
        public string LinkUrl { get; set; }
        public int BravoVetsStatusId { get; set; }
        public System.DateTime PublishDateUtc { get; set; }
        public int PlatformPublishId { get; set; }
        public string AccountName { get; set; }
        public string AccessCode { get; set; }
        public bool IsPublished { get; set; }
        public string PublishError { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime ModifiedDateUtc { get; set; }
        public bool Deleted { get; set; }
    
        public virtual BravoVetsCountry BravoVetsCountry { get; set; }
        public virtual BravoVetsStatu BravoVetsStatu { get; set; }
        public virtual BravoVetsUser BravoVetsUser { get; set; }
        public virtual SocialPlatform SocialPlatform { get; set; }
        public virtual SyndicatedContentPostType SyndicatedContentPostType { get; set; }
    }
}
