//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BravoVets.DomainObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueContentAttachment
    {
        public int QueueContentAttachmentId { get; set; }
        public int QueueContentId { get; set; }
        public Nullable<int> SyndicatedContentAttachmentId { get; set; }
        public string AttachmentFileName { get; set; }
        public string AttachmentExtension { get; set; }
        public byte[] AttachmentFile { get; set; }
        public Nullable<System.DateTime> CreateDateUtc { get; set; }
        public Nullable<System.DateTime> ModifiedDateUtc { get; set; }
    }
}
