//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BravoVets.DomainObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueContentDeliveryLog
    {
        public int QueueContentDeliveryLogId { get; set; }
        public System.Guid DeliverySessionId { get; set; }
        public System.DateTime DeliverySessionStartTimeUtc { get; set; }
        public int QueueContentId { get; set; }
        public bool WasDelivered { get; set; }
        public Nullable<System.DateTime> DeliverySessionTimeUtc { get; set; }
        public string PublishError { get; set; }
    }
}
