//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BravoVets.DomainObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialPlatform
    {
        public SocialPlatform()
        {
            this.QueueContents = new HashSet<QueueContent>();
            this.VeterinarianSocialIntegrations = new HashSet<VeterinarianSocialIntegration>();
        }
    
        public int SocialPlatformId { get; set; }
        public string SocialPlatformName { get; set; }
        public string Url { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime ModifiedDateUtc { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ICollection<QueueContent> QueueContents { get; set; }
        public virtual ICollection<VeterinarianSocialIntegration> VeterinarianSocialIntegrations { get; set; }
    }
}
