//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BravoVets.DomainObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyndicatedContentType
    {
        public SyndicatedContentType()
        {
            this.SyndicatedContents = new HashSet<SyndicatedContent>();
        }
    
        public int SyndicatedContentTypeId { get; set; }
        public string SyndicatedContentTypeName { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
    
        public virtual ICollection<SyndicatedContent> SyndicatedContents { get; set; }
    }
}
