//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BravoVets.DomainObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyndicatedContentPostType
    {
        public SyndicatedContentPostType()
        {
            this.QueueContents = new HashSet<QueueContent>();
            this.SyndicatedContents = new HashSet<SyndicatedContent>();
        }
    
        public int SyndicatedContentPostTypeId { get; set; }
        public string SyndicatedContentPostTypeName { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime ModifiedDateUtc { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ICollection<QueueContent> QueueContents { get; set; }
        public virtual ICollection<SyndicatedContent> SyndicatedContents { get; set; }
    }
}
