//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BravoVets.DomainObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyndicatedContentAttachment
    {
        public int SyndicatedContentAttachmentId { get; set; }
        public int SyndicatedContentId { get; set; }
        public string AttachmentFileName { get; set; }
        public string AttachmentExtension { get; set; }
        public byte[] AttachmentFile { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime ModifiedDateUtc { get; set; }
        public bool DisplayInUi { get; set; }
    }
}
