//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BravoVets.DomainObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class VeterinarianFacility
    {
        public VeterinarianFacility()
        {
            this.VeterinarianFacilityChannels = new HashSet<VeterinarianFacilityChannel>();
        }
    
        public int VeterinarianFacilityId { get; set; }
        public int VeterinarianId { get; set; }
        public string FacilityName { get; set; }
        public string StreetAddress1 { get; set; }
        public string StreetAddress2 { get; set; }
        public string City { get; set; }
        public string StateProvince { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string PrimaryPhoneNumber { get; set; }
        public string SecondaryPhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string FaxNumber { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime ModifiedDateUtc { get; set; }
        public bool Deleted { get; set; }
        public bool IsEditable { get; set; }
    
        public virtual Veterinarian Veterinarian { get; set; }
        public virtual ICollection<VeterinarianFacilityChannel> VeterinarianFacilityChannels { get; set; }
    }
}
