//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BravoVets.DomainObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veterinarian
    {
        public Veterinarian()
        {
            this.BravoVetsUsers = new HashSet<BravoVetsUser>();
            this.Contacts = new HashSet<Contact>();
            this.VeterinarianFacilities = new HashSet<VeterinarianFacility>();
            this.VeterinarianSocialIntegrations = new HashSet<VeterinarianSocialIntegration>();
        }
    
        public int VeterinarianId { get; set; }
        public int BravoVetsCountryId { get; set; }
        public string BusinessName { get; set; }
        public System.DateTime JoinDate { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public System.DateTime ModifiedDateUtc { get; set; }
        public bool Deleted { get; set; }
    
        public virtual BravoVetsCountry BravoVetsCountry { get; set; }
        public virtual ICollection<BravoVetsUser> BravoVetsUsers { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<VeterinarianFacility> VeterinarianFacilities { get; set; }
        public virtual ICollection<VeterinarianSocialIntegration> VeterinarianSocialIntegrations { get; set; }
    }
}
